// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDwZRfAsXXYzS7OsROZIHsN0hbKRGKNwg',
    appId: '1:199915173922:web:73e2a0e2eee8428e4b327b',
    messagingSenderId: '199915173922',
    projectId: 'elite-380601',
    authDomain: 'elite-380601.firebaseapp.com',
    storageBucket: 'elite-380601.appspot.com',
    measurementId: 'G-2Z5SFJBY1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJJAn6_7XKtqSR3REBu7BEhfCAEqehfDE',
    appId: '1:199915173922:android:3a4c4861d9fd4c664b327b',
    messagingSenderId: '199915173922',
    projectId: 'elite-380601',
    storageBucket: 'elite-380601.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtCHh0vfwaF-VQygVm0sFeAOL9XTCbhCg',
    appId: '1:199915173922:ios:7bd86f5e98c087794b327b',
    messagingSenderId: '199915173922',
    projectId: 'elite-380601',
    storageBucket: 'elite-380601.appspot.com',
    iosClientId: '199915173922-du6gm8jauavj2chsrrco92ogrg1t7ff8.apps.googleusercontent.com',
    iosBundleId: 'com.elitetech.elite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtCHh0vfwaF-VQygVm0sFeAOL9XTCbhCg',
    appId: '1:199915173922:ios:7bd86f5e98c087794b327b',
    messagingSenderId: '199915173922',
    projectId: 'elite-380601',
    storageBucket: 'elite-380601.appspot.com',
    iosClientId: '199915173922-du6gm8jauavj2chsrrco92ogrg1t7ff8.apps.googleusercontent.com',
    iosBundleId: 'com.elitetech.elite',
  );
}
